# Library Commons
author=Scuti
maintainer=Scuti <scutiii.code@gmail.com>
url=https://github.com/scutiii2/ArduinoESP32CustomLibraries
license=MIT

# Library Independents
name=ButtonTrigger
version=1.0.0
sentence=Non-blocking button event handler for Arduino and ESP32.
paragraph=Provides onPress, onRelease, onHold, and whileDown events with configurable timing. Works on both Arduino and ESP32 without delays.
category=Signal Input/Output
architectures=*