# Library Commons
author=Scuti
maintainer=Scuti <scutiii.code@gmail.com>
url=https://github.com/scutiii2/ArduinoESP32CustomLibraries
license=MIT

# Library Independents
name=DHTManager
version=1.0.0
sentence=Multi-sensor DHT11 and DHT22 manager for Arduino and ESP32.
paragraph=Provides reliable DHT11 and DHT22 management with filtering, calibration, statistics, environmental calculations, threshold events, and configurable read scheduling.
category=Sensors
architectures=*
depends=Adafruit DHT sensor library