name=RTCLite
version=1.0.0
author=Scuti
maintainer=Scuti <scutiii.code@gmail.com>
sentence=Lightweight non-blocking DS3231 RTC wrapper
paragraph=Simple struct-based RTC wrapper for DS3231 using RTClib with non-blocking initialization and utility formatting.
category=Timing
architectures=*
depends=RTClib
url=https://github.com/scutiii2/RTCLite
license=MIT