name=IRRemote
version=1.0.0
author=Scuti
maintainer=Scuti <scutiii.code@gmail.com>
sentence=Simple Infrared Remote Controller
paragraph=Simple Infrared Remote Controller
category=Display
architectures=*
depends=IRremote
url=https://github.com/scutiii2/ArduinoESP32CustomLibraries
license=MIT