# Library Commons
author=Scuti
maintainer=Scuti <scutiii.code@gmail.com>
url=https://github.com/scutiii2/ArduinoESP32CustomLibraries
license=MIT

# Library Independents
name=ServoManager
version=1.0.0
sentence=Manage one or multiple servo motors with calibration and smooth movement.
paragraph=ServoManager provides centralized management for one or multiple servo motors with runtime calibration, smooth non-blocking movements, relative movements, direct pulse control, and automatic registration.
category=Device Control
architectures=*
depends=ESP32Servo