author=Scuti
maintainer=Scuti <scutiii.code@gmail.com>
url=https://github.com/scutiii2/ArduinoESP32CustomLibraries
license=MIT

name=CommandHTTP
version=1.0.0
sentence=HTTP bridge for CommandController.
paragraph=Provides a simple HTTP POST endpoint for executing CommandController commands.
category=Communication
architectures=esp32