name=ToneLite
version=1.0.0
author=Scuti
maintainer=Scuti <scutiii.code@gmail.com>
sentence=Non-blocking tone player for Arduino and ESP32.
paragraph=Play melodies from arrays of notes.
category=Signal Input/Output
architectures=*
url=https://github.com/scutiii2/ArduinoESP32CustomLibraries
license=MIT